# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  paging:
    colorArg: always
    pager: delta --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --paging=never --features $(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo catppuccin-mocha || echo catppuccin-latte)
